version: '3'

services:
  socks-db:
    image: postgres:11.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: hackaton
      POSTGRES_USER: hackaton
      POSTGRES_PASSWORD: ${DB_PASS}

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: hackaton
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}